Update to File widget for uploading multiple files
mljar/mercury pull request #387
Opened 2023-10-27 23:33 UTC by rmkolany

Link to Issue #347 
To help move this issue along I updated the `File` widget to accept multiple files. I added an argument `multiple` to allow the user to specify if they would like to allow multiple files to be uploaded. `multiple=False` by default and should have no impact on users who are using this widget for one file now. `filename`, `filepath`, and `value` output lists if `multiple=True`. I considered using a different method but wanted to retain the current functionality as much as possible. 

### `File` Widget Use with Multiple Files
**Input**
`myFile = mercury.File(label="Upload File Here", multiple=True)`

**Handling Files After Upload**
`myFile.filename`

> ['file1_name.ext','file2_name.ext']

`myFile.filepath`

> ['path\\to\\files\\temp_dir\\file1_name.ext','path\\to\\files\\temp_dir\\file2name.ext']

`myFile.value`

> [<memory at 0x0000012345678910>,<memory at 0x0000010987654321>]

`myFile.temp_dir`

> 'path\\to\\files\\temp_dir'

I was able to get this to work in my environment without any issues in Jupyter Lab but the file uploader would not accept multiple files in the Mercury UI. It looks like some updates may be needed on the React side of things but I am not familiar with React to make the necessary changes.

2023-10-27 23:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mljar/mercury?pullRequest=387) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/mljar/mercury?pullRequest=387) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mljar/mercury?pullRequest=387) it.</sub>

2023-10-28 11:08 UTC, pplonski commented
Hi @rmkolany, thanks for PR. I believe that there are needed changes in the frontend code, to make it work. The File widget in the frontend (React code) should use `multiple` parameter.

2023-10-31 07:35 UTC, pplonski requested changes
Is it working for you? do you have some screenshots with multiple file upload?

2023-10-31 07:35 UTC, pplonski commented on frontend/package.json
you can't import package from local paths, because it will not work for other folks

2023-10-31 14:45 UTC, rmkolany commented on frontend/package.json
I tried a few different methods including running pip install for my branch and just cloning the repo and running setup.py to build the package. The latter method seems to have worked better but when I go to run mercury I get the 'TemplateDoesNotExist' error in the browser due to the templates and frontend-dist folders not being created. My attempt at changing the React code is within commit 7d78406 by adding to the `multiple` parameter to the file widget. I have never worked in React and will likely need help to get this to work for others.

2023-11-01 14:16 UTC, pplonski commented on frontend/package.json
Oh, sorry! I should explain it earlier ... You need to build the frontend and copy all html, js, css files into Django directory, here are steps:

```
# run from main directory

# 1. remove previous frontend static files
rm -rf mercury/frontend-dist
# 2. go to fronted directory
cd frontend
# 3. install required packages
yarn install
# 4. build fronted files and copy them (copy is done in the local-build command)
yarn local-build
```

After above steps you should see changes in frontend when running mercury locally with command (`mercury run`).

2026-04-30 09:12 UTC, closed without merging

2026-04-30 09:13 UTC, pplonski commented
We have released a new version of Mercury in which we directly reuse `ipywidgets`.